apiVersion: v1
kind: ReplicationController
metadata:
  name: pv-nginx
spec:
  replicas: 2
  template:
    metadata:
      name: pv-rc-nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: pv-rc-nginx-pod
          image: nginx
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: mydata
          ports:
            - containerPort: 80
      volumes:
      - name: mydata
        persistentVolumeClaim:
          claimName: mypvc1
