apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
  - name: pv-bussybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: /foo
      name: mydata
  volumes:
  - name: mydata
    persistentVolumeClaim:
      claimName: mypvc1
