apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-vars
data:
  loglevel: info
  datadir: /var/foo
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-test
spec:
  containers:
    - name: cm-test
      image: busybox
      command: [ "/bin/sh","-c","env|grep APP"]
      env:
        - name: APPLOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: cm-vars
              key: loglevel
        - name: APPDATADIR
          valueFrom:
            configMapKeyRef:
              name: cm-vars
              key: datadir
